name: ☎ Question
description: Have a Question for us?
title: "[Question] : "
labels: ['type: Question', 'status: Waiting Triage']
body:
- type: dropdown
  id: platform
  attributes:
    label: For which platform you have question with?
    options:
      - FireHub Core
  validations:
    required: true
- type: textarea
  attributes:
    label: Ask your question
    description: A clear and concise description of your question.
  validations:
    required: true
