name: 📌 Enhancement Request
description: Request new enhancement for our aplications
title: "[Enhancement] : "
labels: ['type: Enhancement', 'status: Waiting Triage']
body:
- type: dropdown
  id: platform
  attributes:
    label: For which platform you are requesting enhancement?
    options:
      - FireHub Core
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution and feature you'd like to be enhanced
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the enhancement request here.
  validations:
    required: false
