name: 📌 Feature Request
description: Request new feature for our aplications
title: "[FEATURE] : "
labels: ['type: Feature', 'status: Waiting Triage']
body:
- type: dropdown
  id: platform
  attributes:
    label: For which platform you are requesting feature?
    options:
      - FireHub Core
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution you'd like
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Is your feature request related to a problem?
    description: Please describe a clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the feature request here.
  validations:
    required: false
