name: 🚨 Security Issue
description: If you have found a security or an abuse risk related bug in any of our products and want to report it to us.
title: "[Security] : "
labels: ['type: Security', 'status: Waiting Triage']
body:
- type: dropdown
  id: platform
  attributes:
    label: For which platform you have security issue?
    options:
      - FireHub Core
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the security issues you encountered
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: dropdown
  attributes:
    label: Affected areas
    description: Check affected areas of security issue.
    options:
      - Users Personal Data
      - Sensitive Data Exposure
      - Data Injection
      - Access Control
      - Authentication Issues
      - Cross-site Scripting
      - Buffer Overflow
      - Security Misconfiguration
      - Vulnerabilities
      - Other
    multiple: true
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the enhancement request here.
  validations:
    required: false
