name: 📌 Optimization Request
description: Request optimization for our aplications
title: "[Optimization] : "
labels: ['type: Optimization', 'status: Waiting Triage']
body:
- type: dropdown
  id: platform
  attributes:
    label: For which platform you are requesting optimization?
    options:
      - FireHub Core
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe the solution and feature you'd like to be optimized
    description: A clear and concise description of what you want to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe alternatives you've considered
    description: A clear and concise description of any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context
    description: Add any other context or screenshots about the enhancement request here.
  validations:
    required: false
