name: ☎ General Support
description: General Purpose Support for various things related to us and our products
title: "[Support] : "
labels: ['type: Support', 'status: Waiting Triage']
body:
- type: dropdown
  id: platform
  attributes:
    label: For which platform you need support with?
    options:
      - FireHub Core
  validations:
    required: true
- type: textarea
  attributes:
    label: Describe your inquiry
    description: A clear and concise description of your inquiry.
  validations:
    required: true
